# Generated by Django 4.1.3 on 2023-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='avatar.avif', null=True, upload_to='blog'),
        ),
    ]
